# @package environment
# Training Environment Configuration
# Optimized configuration for training ARC agents

# Episode Settings - Optimized for Training
max_episode_steps: 75 # Shorter episodes for faster training iterations
auto_reset: true # Automatically reset environment after episode ends

# Environment Behavior - More Permissive for Training
strict_validation: false # Less strict validation to allow exploration
allow_invalid_actions: true # Allow invalid actions for exploration (with penalties)

# Debug Level - Enhanced for Training
debug_level: "verbose" # Verbose debugging for training insights
