# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2025.05.02-13-g4bc2312
_src_path: gh:scientific-python/cookie
backend: hatch
email: aadimator@gmail.com
full_name: Aadam
license: MIT
org: aadimator
project_name: JaxARC
project_short_description: MARL environment for ARC dataset in JAX
url: https://github.com/aadimator/JaxARC
vcs: true
