# @package _global_
# Local-only logging configuration - no wandb integration

defaults:
  - /storage: development

# Wandb integration disabled
wandb:
  enabled: false
  project_name: "jaxarc-local"
  offline_mode: true

# Local logging settings
logging:
  structured_logging: true
  log_format: "json"
  compression: true
  include_full_states: false
  log_level: "INFO"

# Episode management for local storage
episode:
  base_output_dir: "outputs/episodes"
  max_episodes_per_run: 100
  cleanup_policy: "size_based"
  max_storage_gb: 2.0

# Async logging for performance
async_logger:
  queue_size: 500
  worker_threads: 1
  batch_size: 5
  flush_interval: 10.0
  enable_compression: true