# @package _global_
# Full wandb integration configuration for research

defaults:
  - /visualization: debug_verbose

# Full wandb configuration
wandb:
  enabled: true
  project_name: "jaxarc-research"
  entity: null  # Set via environment variable or override
  tags: ["jaxarc", "research", "full-logging"]
  notes: "Full JaxARC experiment with comprehensive wandb logging"
  group: "research-experiments"
  job_type: "research"
  
  # Frequent logging for research
  log_frequency: 5
  image_format: "both"  # Both PNG and SVG
  max_image_size: [1024, 768]
  
  # Advanced logging enabled
  log_gradients: true
  log_model_topology: true
  log_system_metrics: true
  
  # Robust error handling
  offline_mode: false
  retry_attempts: 5
  retry_delay: 2.0
  
  # Full storage
  save_code: true
  save_config: true

# Comprehensive local logging
logging:
  structured_logging: true
  log_format: "json"
  compression: true
  include_full_states: true  # Full state logging for research
  log_level: "DEBUG"

# Extended episode management
episode:
  base_output_dir: "outputs/research_episodes"
  max_episodes_per_run: 1000
  cleanup_policy: "manual"  # Manual cleanup for research
  max_storage_gb: 20.0

# High-performance async logging
async_logger:
  queue_size: 2000
  worker_threads: 4
  batch_size: 20
  flush_interval: 2.0
  enable_compression: true