# @package _global_
# Basic wandb integration configuration

defaults:
  - /visualization: debug_standard

# Basic wandb configuration
wandb:
  enabled: true
  project_name: "jaxarc-experiments"
  entity: null  # Use default entity
  tags: ["jaxarc", "basic"]
  notes: "Basic JaxARC experiment with wandb logging"
  group: null
  job_type: "training"
  
  # Logging settings
  log_frequency: 10
  image_format: "png"
  max_image_size: [800, 600]
  
  # Advanced options (disabled for basic config)
  log_gradients: false
  log_model_topology: false
  log_system_metrics: true
  
  # Error handling
  offline_mode: false
  retry_attempts: 3
  retry_delay: 1.0
  
  # Storage
  save_code: true
  save_config: true

# Local logging as backup
logging:
  structured_logging: true
  log_format: "json"
  compression: true
  include_full_states: false
  log_level: "INFO"

# Episode management
episode:
  base_output_dir: "outputs/episodes"
  max_episodes_per_run: 200
  cleanup_policy: "oldest_first"
  max_storage_gb: 5.0

# Async logging
async_logger:
  queue_size: 1000
  worker_threads: 2
  batch_size: 10
  flush_interval: 5.0
  enable_compression: true