# ARC-AGI-1 Dataset Configuration (GitHub Format)
# This configuration contains dataset-specific settings for ARC-AGI-1

# Dataset Information
dataset_name: "ARC-AGI-1"
dataset_year: 2024
description: "ARC-AGI-1 dataset from GitHub (fchollet/ARC-AGI)"

default_split: "training" # Default split to use

# Data Paths - GitHub format uses directories
data_root: "data/raw/ARC-AGI-1"
training:
  path: "${dataset.data_root}/data/training"
evaluation:
  path: "${dataset.data_root}/data/evaluation"

# Parser Configuration
parser:
  _target_: jaxarc.parsers.ArcAgiParser
  description: "General ARC-AGI parser supporting both ARC-AGI-1 and ARC-AGI-2"

# Grid Configuration
grid:
  max_grid_height: 30 # Maximum height for JAX array padding
  max_grid_width: 30 # Maximum width for JAX array padding
  min_grid_height: 1 # Minimum height for valid grids
  min_grid_width: 1 # Minimum width for valid grids
  max_colors: 10 # Maximum number of colors (ARC uses 0-9)
  background_color: 0 # Default background color (black in ARC)

# Task Configuration for JAX Environment
max_train_pairs: 10 # Maximum number of training pairs per task
max_test_pairs: 3 # Maximum number of test pairs per task
