# ARC-AGI-1 Dataset Configuration (2024 Dataset)
# This configuration contains dataset-specific settings for ARC-AGI-1

# Dataset Information
dataset_name: "ARC-AGI-1"
dataset_year: 2024
description: "ARC-AGI-1 dataset (2024) for abstract reasoning tasks"

default_split: "training" # Default split to use

# Data Paths (adjust these to your local dataset location)
data_root: "data/raw/arc-prize-2024"
training:
  challenges: "${dataset.data_root}/arc-agi_training_challenges.json"
  solutions: "${dataset.data_root}/arc-agi_training_solutions.json"
evaluation:
  challenges: "${dataset.data_root}/arc-agi_evaluation_challenges.json"
  solutions: "${dataset.data_root}/arc-agi_evaluation_solutions.json"
testing:
  challenges: "${dataset.data_root}/arc-agi_test_challenges.json"
sample_submission: "${dataset.data_root}/sample_submission.json"

# Parser Configuration
parser:
  _target_: jaxarc.parsers.ArcAgiParser
  description: "General ARC-AGI parser supporting both ARC-AGI-1 and ARC-AGI-2"

# Grid Configuration
max_grid_size: 30 # ARC grids are up to 30x30
max_grid_height: 30 # Maximum height for JAX array padding
max_grid_width: 30 # Maximum width for JAX array padding

# Task Configuration for JAX Environment
max_train_pairs: 10 # Maximum number of training pairs per task
max_test_pairs: 3 # Maximum number of test pairs per task
max_action_params: 10 # Maximum parameters for a single action
