# Mini ARC Dataset Configuration
# This configuration contains dataset-specific settings for Mini ARC
# Smaller grids and simpler tasks for testing and rapid experimentation

# Dataset Information
dataset_name: "Mini-ARC"
dataset_year: 2024
description:
  "Mini ARC dataset with smaller grids for testing and experimentation"

default_split: "training" # Default split to use

# Data Paths (adjust these to your local dataset location)
data_root: "data/raw/mini-arc"
training:
  challenges: "${dataset.data_root}/mini_arc_training_challenges.json"
  solutions: "${dataset.data_root}/mini_arc_training_solutions.json"
evaluation:
  challenges: "${dataset.data_root}/mini_arc_evaluation_challenges.json"
  solutions: "${dataset.data_root}/mini_arc_evaluation_solutions.json"
testing:
  challenges: "${dataset.data_root}/mini_arc_test_challenges.json"
sample_submission: "${dataset.data_root}/sample_submission.json"

# Parser Configuration
parser:
  _target_: jaxarc.parsers.ArcAgiParser
  description: "General ARC-AGI parser supporting Mini ARC format"

# Grid Configuration - Smaller for testing
grid:
  max_grid_height: 10 # Smaller maximum height for faster processing
  max_grid_width: 10 # Smaller maximum width for faster processing
  min_grid_height: 1 # Minimum height for valid grids
  min_grid_width: 1 # Minimum width for valid grids
  max_colors: 10 # Maximum number of colors (ARC uses 0-9)
  background_color: 0 # Default background color (black in ARC)

# Task Configuration for JAX Environment - Fewer pairs for simpler tasks
max_train_pairs: 5 # Fewer training pairs for simpler tasks
max_test_pairs: 2 # Fewer test pairs for simpler tasks
