# ARC Environment Configuration
# Clean structured configuration

# Environment target class (for backward compatibility)
_target_: jaxarc.envs.ArcEnvironment

# Episode Settings
max_episode_steps: 100 # Maximum steps per episode
auto_reset: true # Automatically reset environment after episode ends

# Logging and Debugging
log_operations: true # Log operations for debugging
log_grid_changes: false # Log detailed grid changes
log_rewards: false # Log reward calculations

# Environment Behavior
strict_validation: true # Strict validation of actions and states
allow_invalid_actions: false # Whether to allow invalid actions (vs raising errors)

# Legacy Settings (for backward compatibility with existing code)
similarity_threshold: 1.0 # Threshold for considering task solved
