# ARC Environment Configuration
# Environment-specific settings only (no dataset-related duplication)

# Environment target class
_target_: jaxarc.envs.ArcEnvironment

# Episode Settings
max_episode_steps: 100 # Maximum steps per episode

# Reward Configuration
reward_on_submit_only: true # Only reward on submit operation
similarity_threshold: 1.0 # Threshold for considering task solved
step_penalty: -0.01 # Small penalty per step
success_bonus: 10.0 # Bonus for successful completion

# Action Space
mask_threshold: 0.5 # Threshold for continuous mask conversion
use_continuous_mask: false # Use boolean masks for simplicity

# Performance Settings
jit_compile: true # Enable JAX JIT compilation
use_static_shapes: true # Use static shapes for JAX optimization
flood_fill_max_iterations: 64 # Fixed iterations for flood fill

# Debugging
log_operations: true # Log operations for debugging
visualize_grids: true # Enable grid visualization
