# ARC-AGI-2 Environment Configuration (2025 Dataset)
# This configuration works with ARC-AGI-2 data downloaded from Kaggle

# Dataset Information
dataset_name: "ARC-AGI-2"
dataset_year: 2025
description: "ARC-AGI-2 dataset (2025) for abstract reasoning tasks"

default_split: "training" # Default split to use

# Data Paths (adjust these to your local dataset location)
data_root: "data/raw/arc-prize-2025"
training:
  challenges: "${environment.data_root}/arc-agi_training_challenges.json"
  solutions: "${environment.data_root}/arc-agi_training_solutions.json"
evaluation:
  challenges: "${environment.data_root}/arc-agi_evaluation_challenges.json"
  solutions: "${environment.data_root}/arc-agi_evaluation_solutions.json"
testing:
  challenges: "${environment.data_root}/arc-agi_test_challenges.json"
sample_submission: "${environment.data_root}/sample_submission.json"

# Parser Configuration
parser:
  _target_: jaxarc.parsers.ArcAgiParser
  description: "General ARC-AGI parser supporting both ARC-AGI-1 and ARC-AGI-2"

# Grid Configuration
max_grid_size: 30 # ARC grids are up to 30x30
max_grid_height: 30 # Maximum height for JAX array padding
max_grid_width: 30 # Maximum width for JAX array padding

# Task Configuration for JAX Environment
max_train_pairs: 10 # Maximum number of training pairs per task
max_test_pairs: 4 # Maximum number of test pairs per task
max_hypotheses: 32 # Maximum number of concurrent hypotheses
max_action_params: 10 # Maximum parameters for a single action
max_proposal_data_dim: 10 # Maximum dimension for hypothesis data

# Environment Configuration (placeholder for future MARL environment)
environment:
  max_steps_per_episode: 200
  num_agents: 4
  collaboration_enabled: true
