# Raw Environment Configuration
# Minimal environment configuration with only basic operations
# Uses raw action set: fill colors (0-9), resize grid, and submit

defaults:
  - reward: standard
  - action: raw

# Environment target class (for backward compatibility)
_target_: jaxarc.envs.ArcEnvironment

# Episode Settings
max_episode_steps: 50 # Shorter episodes for minimal action set
auto_reset: true # Automatically reset environment after episode ends

# Logging and Debugging
log_operations: true # Log operations for debugging
log_grid_changes: false # Log detailed grid changes
log_rewards: false # Log reward calculations

# Environment Behavior
strict_validation: true # Strict validation of actions and states
allow_invalid_actions: false # No invalid actions allowed in raw mode

# Legacy Settings (for backward compatibility with existing code)
similarity_threshold: 1.0 # Threshold for considering task solved
