# Training-optimized reward configuration
# Designed for efficient multi-demonstration training with step-by-step feedback

# Basic reward settings optimized for training
reward_on_submit_only: false  # Step-by-step rewards for better learning signal
step_penalty: -0.005  # Smaller penalty to encourage exploration
success_bonus: 15.0  # Higher success bonus for motivation
similarity_weight: 1.0

# Enhanced progress tracking
progress_bonus: 0.2  # Reward similarity improvements

# Control operation penalty removed (legacy field)

# Training mode settings
training_similarity_weight: 1.0  # Full similarity feedback

# Pair completion incentives
demo_completion_bonus: 2.0  # Good bonus for demo completion
test_completion_bonus: 10.0  # High bonus for test completion

# Efficiency incentives
efficiency_bonus_threshold: 30  # Encourage efficient solutions
efficiency_bonus: 3.0  # Good efficiency bonus

# Reward frequencies
training_reward_frequency: "step"  # Continuous feedback
evaluation_reward_frequency: "submit"  # Only on completion