# @package visualization
# Development visualization configuration - rich debugging with reasonable performance

# Core visualization settings
debug_level: "verbose"
enabled: true

# Output settings
output_formats: ["svg", "png"]
image_quality: "high"
output_dir: "outputs/development"

# Visual enhancements for development
show_coordinates: true
show_operation_names: true
highlight_changes: true
include_metrics: true
color_scheme: "default"

# Episode visualization
visualize_episodes: true
episode_summaries: true
step_visualizations: true

# Development-friendly logging (frequent but not overwhelming)
log_frequency: 5
log_episode_end: true
log_episode_start: true
log_key_moments: true

# Comparison and analysis features
enable_comparisons: true
save_intermediate_states: true

# Memory and performance (generous for development)
lazy_loading: false  # Immediate loading for faster debugging
memory_limit_mb: 1000
max_storage_gb: 5.0

# Async processing
async_processing:
  enabled: true
  queue_size: 1000
  worker_threads: 2
  batch_size: 10
  flush_interval: 5.0

# Episode management
episode_management:
  base_output_dir: "outputs/development"
  run_name: null  # Auto-generated
  episode_dir_format: "episode_{episode:04d}"
  step_file_format: "step_{step:03d}"
  max_episodes_per_run: 100
  cleanup_policy: "size_based"

# Performance monitoring
performance_monitoring:
  enabled: true
  target_overhead: 0.15  # Allow higher overhead for development
  measurement_window: 50
  auto_adjust: false  # Don't auto-adjust during development

# Wandb integration (optional for development)
wandb:
  enabled: false  # Disabled by default for development
  project_name: "jaxarc-development"
  tags: ["development", "debug"]
  log_frequency: 10
  offline_mode: true
  image_format: "png"
  max_image_size: [1024, 768]