# @package visualization
# Research visualization configuration - comprehensive logging and analysis

# Core visualization settings
debug_level: "full"
enabled: true

# Output settings (comprehensive for research)
output_formats: ["svg", "png"]
image_quality: "high"
output_dir: "outputs/research"

# Full visual features for analysis
show_coordinates: true
show_operation_names: true
highlight_changes: true
include_metrics: true
color_scheme: "default"

# Comprehensive episode visualization
visualize_episodes: true
episode_summaries: true
step_visualizations: true

# Detailed logging for research
log_frequency: 1  # Log every step
log_episode_end: true
log_episode_start: true
log_key_moments: true

# Enable all analysis features
enable_comparisons: true
save_intermediate_states: true

# Generous memory and storage for research
lazy_loading: false
memory_limit_mb: 2000
max_storage_gb: 10.0

# Robust async processing
async_processing:
  enabled: true
  queue_size: 2000
  worker_threads: 3
  batch_size: 5  # Smaller batches for detailed logging
  flush_interval: 2.0

# Research episode management
episode_management:
  base_output_dir: "outputs/research"
  run_name: null  # Will be set by experiment
  episode_dir_format: "episode_{episode:05d}"
  step_file_format: "step_{step:04d}"
  max_episodes_per_run: 1000
  cleanup_policy: "manual"  # Manual cleanup for research

# Performance monitoring (allow higher overhead)
performance_monitoring:
  enabled: true
  target_overhead: 0.25  # Allow significant overhead for research
  measurement_window: 20
  auto_adjust: false  # Don't auto-adjust during research

# Comprehensive wandb integration
wandb:
  enabled: true
  project_name: "jaxarc-research"
  tags: ["research", "analysis"]
  log_frequency: 5
  offline_mode: false
  image_format: "both"  # Both PNG and SVG
  max_image_size: [1200, 900]
  log_gradients: true
  log_model_topology: true
  log_system_metrics: true
  save_artifacts: true
  artifact_types: ["model", "visualization", "analysis"]

# Additional research features
research_features:
  enable_replay_system: true
  save_action_sequences: true
  track_state_transitions: true
  generate_analysis_reports: true
  compare_across_runs: true