from __future__ import annotations

from collections.abc import Sequence
from typing import NewType

import chex
import jax.numpy as jnp


@chex.dataclass
class Grid:
    """Represents a 2D grid of colors.

    Attributes:
        array: A JAX ndarray representing the grid.
               Shape is (height, width). Values are integers (colors).
    """

    array: jnp.ndarray

    def __post_init__(self) -> None:
        chex.assert_rank(self.array, 2)
        # ARC colors are typically small integers (0-9).
        # We'll assert integer type, specific range checks can be done by the parser if needed.
        chex.assert_type(self.array, jnp.integer)


@chex.dataclass
class TaskPair:
    """Represents an input-output pair of grids for an ARC task.

    Attributes:
        input: The input grid.
        output: The output grid. Can be None for test inputs before solutions are known.
    """

    input: Grid
    output: Grid | None


@chex.dataclass
class ArcTask:
    """Represents a parsed ARC task.

    Attributes:
        task_id: An optional identifier for the task (e.g., filename).
        train_pairs: A sequence of training input-output grid pairs.
        test_pairs: A sequence of test input-output grid pairs.
                   For challenges, the 'output' in test_pairs is the target solution.
    """

    train_pairs: Sequence[TaskPair]
    test_pairs: Sequence[TaskPair]
    task_id: str | None = None


# --- Core Data Types for Agent Actions and Hypotheses ---
# Simplified for Phase 1 - can be expanded later

# Type Aliases for IDs
AgentID = NewType("AgentID", int)


@chex.dataclass
class Hypothesis:
    """
    Represents a basic hypothesis generated by an agent.
    Simplified for Phase 1 - can be expanded with more fields later.
    """

    agent_id: AgentID  # ID of the agent generating the hypothesis
    step_number: jnp.ndarray  # Step when hypothesis was created (int32 scalar)
    confidence: jnp.ndarray  # Confidence score (float32 scalar, 0.0 to 1.0)

    # Optional data payload - can be used flexibly
    data: jnp.ndarray | None = None  # Generic data array
    description: str | None = None  # Optional textual description

    def __post_init__(self) -> None:
        chex.assert_type(self.step_number, jnp.int32)
        chex.assert_shape(self.step_number, ())  # Ensure scalar
        chex.assert_type(self.confidence, jnp.float32)
        chex.assert_shape(self.confidence, ())  # Ensure scalar
