# @package logging
# Basic logging configuration with moderate detail

# Core logging settings
structured_logging: true
log_format: "json"
log_level: "INFO"
compression: true
include_full_states: false

# What to log
log_operations: false
log_grid_changes: false
log_rewards: false
log_episode_start: true
log_episode_end: true
log_key_moments: true

# Logging frequency and timing
log_frequency: 10

# Async logging settings
queue_size: 1000
worker_threads: 2
batch_size: 10
flush_interval: 5.0
enable_compression: true
